---
version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "5"

services:
  nginx:
    logging: *logging
    image: nginx:1.25.3-bookworm
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../output:/var/www/output:ro"
    ports:
      - "8080:8080"
    networks:
      - vidi

  minio:
    logging: *logging
    image: quay.io/minio/minio:RELEASE.2024-01-01T16-36-33Z
    volumes:
      - "minio-data:/data"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  postgres:
    logging: *logging
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "vidi-db:/var/lib/postgresql/data"
      - "./initdb:/docker-entrypoint-initdb.d:ro"
    ports:
      - "5400:5432"
    networks:
      - vidi

  userapi:
    logging: *logging
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: docker/userapi.Dockerfile
      target: dev
    environment:
      VIDI_API_PREFIX: /api/users
      VIDI_DATABASE_DSN: postgres://userapi:userapi@postgres:5432/userapi?sslmode=disable
      VIDI_DATABASE_SALT: q1w2e3r4t5
      VIDI_SERVER_ADDRESS: ":8080"
    expose:
      - 8080
    networks:
      - vidi
    depends_on:
      - postgres

volumes:
  minio-data: {}
  vidi-db: {}

networks:
  vidi:
    name: vidi-net
    driver: bridge
