---
version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "5"

services:
  nginx:
    logging: *logging
    restart: unless-stopped
    image: nginx:1.25.3-bookworm
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./player:/var/www/player:ro"
    ports:
      - "8080:80"
    networks:
      - vidi

networks:
  vidi:
    name: vidi-net
    driver: bridge
